pipeline {
    agent any
    tools {
        maven 'Maven3'  // Ensure Maven is installed
        jdk 'Java_Home'     // Ensure JDK is installed
    }
    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/gitober/Student-Information-System.git',branch:'main'
            }
        }
        stage('Build') {
            steps {
                dir ('student-information-app') {
                    bat 'mvn clean package'
                }
            }
        }
        stage('Run Unit Tests') {
            steps {
                dir('student-information-app') {  // Ensure we are in the correct directory
                    bat 'mvn test'
                }
            }
            post {
                always {
                    dir('student-information-app') {  // Ensure we are in the correct directory
                        junit 'target/surefire-reports/*.xml'  // Capture test reports
                    }
                }
            }
        }
        stage('Code Coverage Report') {
            steps {
                dir('student-information-app') {  // Ensure we are in the correct directory
                    bat 'mvn jacoco:report'
                }
            }
            post {
                always {
                    dir('student-information-app') {  // Ensure we are in the correct directory
                        jacoco(execPattern: 'target/jacoco.exec')
                    }
                }
            }
        }
    }
}


