name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # Allows for manual runs

permissions:
  pull-requests: read  # Required to annotate pull requests with analysis results

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'zulu'

      - name: Build Project with Maven
        run: mvn clean install
        working-directory: student-information-app  # Set working directory to where pom.xml is

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=eetuam1_Student-Information-System
            -Dsonar.organization=eetuam1
            -Dsonar.sources=student-information-app/src
            -Dsonar.java.binaries=student-information-app/target
            -Dsonar.exclusions=**/vaadin/**,**/node_modules/**,**/generated/**,**/target/**,**/src/test/**
            -Dsonar.coverage.jacoco.xmlReportPaths=student-information-app/target/jacoco-report/jacoco.xml
            -Dsonar.coverage.exclusions=**/vaadin/**,**/node_modules/**,**/generated/**,**/target/**,**/src/test/**


